In [2]:
# Dependencies

import pandas as pd
import numpy as np
import seaborn as sns

In [4]:
pd.set_option('display.max_columns', 100)
df = pd.read_csv('../data/fake_job_postings.csv')
df.sample(3)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
5603,5604,Mobile Product Manager,"GB, LND, London",Product,NaN,Want to build a 21st century financial service...,TransferWise is a fast growing startup helping...,- 3+ years in product management with mobile f...,#NAME?,0,1,0,NaN,NaN,NaN,NaN,NaN,0
9926,9927,Office Administrator/Accounts Receivable Liaison,"US, IL, Chicago",NaN,NaN,NaN,Market News International is a financial news ...,Ability to prioritize tasks and use time manag...,Employment Status: Full time consultant with t...,0,1,1,Contract,NaN,NaN,NaN,NaN,0
11056,11057,Marketing & Communications Manager - Rippleshot,"US, IL, Chicago",Rippleshot,40000-60000,The story of the Great Chicago Fire of 1871 is...,JOB DESCRIPTIONRippleshot is looking for a Mar...,DESIRED EXPERIENCE2-5 years of marketing exper...,NaN,0,1,0,Full-time,Associate,Bachelor's Degree,Information Technology and Services,Marketing,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [8]:
df.describe()

,job_id,telecommuting,has_company_logo,has_questions,fraudulent
count,17880.000000,17880.000000,17880.000000,17880.000000,17880.000000
mean,8940.500000,0.042897,0.795302,0.491723,0.048434
std,5161.655742,0.202631,0.403492,0.499945,0.214688
min,1.000000,0.000000,0.000000,0.000000,0.000000
25%,4470.750000,0.000000,1.000000,0.000000,0.000000
50%,8940.500000,0.000000,1.000000,0.000000,0.000000
75%,13410.250000,0.000000,1.000000,1.000000,0.000000
max,17880.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df.describe(include='object')

,title,location,department,salary_range,company_profile,description,requirements,benefits,employment_type,required_experience,required_education,industry,function
count,17880,17534,6333,2868,14572,17879,15184,10668,14409,10830,9775,12977,11425
unique,11231,3105,1337,874,1709,14801,11967,6204,5,7,13,131,37
top,English Teacher Abroad,"GB, LND, London",Sales,0-0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology
freq,311,718,551,142,726,379,410,726,11620,3809,5145,1734,1749

In [11]:
# get duplicates
df.duplicated().sum()

np.int64(0)

In [14]:
# missing values sum
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [15]:
# handle missing
# only object value types are missing
df.fillna('Missing', inplace=True)

In [19]:
df.location.str.count(",").value_counts()

location
2     17320
0       440
3       104
4         7
5         4
6         2
8         1
15        1
10        1
Name: count, dtype: int64